pool:
  vmImage: ubuntu-latest

stages:
- stage: ci
  displayName: Continious Integration
  jobs:
  - job: build
    displayName: Build Project Assets
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
    - script: |
        dotnet publish \
        --configuration Release \
        --output out \
        --runtime win-x64 \
        --self-contained \
        -p:EnableCompressionInSingleFile=true \ 
        -p:PublishSingleFile=true \
        -p:PublishReadyToRun=true \
        -p:DebugType=true
      displayName: Publish .Net Console Project

