pool:
  vmImage: ubuntu-latest

stages:
- stage: ci
  displayName: Continious Integration
  jobs:
  - job: build
    displayName: Build Project Assets
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
    - script: |
        dotnet publish \
        --configuration Release \
        --output out \
        --runtime win-x64 \
        --self-contained \
        -p:EnableCompressionInSingleFile=true \
        -p:PublishSingleFile=true \
        -p:PublishReadyToRun=true \
        -p:DebugType=embedded
      displayName: Publish .Net Console Project
    - publish: out/Contoso.Spaces.Console.exe
      displayName: Upload console app artifact
      artifact: console-app
    - script: |
        dotnet pack \
        --output pkg \
        -p:Version=1.0.0
      displayName: Package dotnet tool
    - publish: pkg/Contoso.Spaces.Console.1.0.0.nupkg
      displayName: Upload nuget package artifact
      artifact: nuget-package

  - job: release
    displayName: Release on Nuget
    dependsOn: build
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
    - download: current
      displayName: Download nuget package artifact
      artifact: nuget-package
